my_project:
  authapp:
    __init__.py:
    models.py:
    templates:
      authapp:
        base.html:
        index.html:
    views.py:
  mainapp:
    __init__.py:
    models.py:
    templates:
      mainapp:
        base.html:
        index.html:
    views.py:
  settings:
    __init__.py:
    dev.py:
    prod.py:
